In [1]:
import sys, torch
import numpy as np
import matplotlib.pyplot as plt
print("Python:", sys.executable)
print("Torch version:", torch.__version__)
print("MPS available:", torch.backends.mps.is_available())

# Detect GPU (MPS for Apple Silicon)
device = "mps" if torch.backends.mps.is_available() else "cpu"
print("Using device:", device)

Python: /Users/aashishmalhan/projects/mml/venv/bin/python
Torch version: 2.9.1
MPS available: True
Using device: mps


In [7]:
# Eigen decomposition
A = torch.tensor([[2.0, -2.0], 
                  [-2.0, 5.0]])
eigenvalues, eigenvectors = torch.linalg.eig(A)
print("Matrix A:\n", A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Matrix A:
 tensor([[ 2., -2.],
        [-2.,  5.]])
Eigenvalues: tensor([1.+0.j, 6.+0.j])
Eigenvectors: tensor([[-0.8944+0.j,  0.4472+0.j],
        [-0.4472+0.j, -0.8944+0.j]])


In [9]:
# SVD decomposition
B = torch.tensor([[3.0, 0.0],
                  [4.0, 0.0]])
U, S, Vh = torch.linalg.svd(B)
print("Matrix B:\n", B)
print("U matrix:\n", U)
print("Singular values:", S)
print("Vh matrix:\n", Vh)

Matrix B:
 tensor([[3., 0.],
        [4., 0.]])
U matrix:
 tensor([[-0.6000, -0.8000],
        [-0.8000,  0.6000]])
Singular values: tensor([5., 0.])
Vh matrix:
 tensor([[-1., -0.],
        [ 0.,  1.]])


In [ ]:
def plot_vectors(vectors, colors, labels, title="", xlim=(-10, 10), ylim=(-10, 10)):
    plt.figure(figsize=(6,6))
    plt.axhline(0, color='black', linewidth=0.5)
    plt.axvline(0, color='black', linewidth=0.5)

    for v, col, lab in zip(vectors, colors, labels):
        plt.quiver(0, 0, v[0], v[1], angles='xy', scale_units='xy',
                   scale=1, color=col, label=lab)

    plt.xlim(xlim)
    plt.ylim(ylim)
    plt.grid(True, linestyle='--', alpha=0.4)
    plt.legend()
    plt.title(title)
    plt.gca().set_aspect('equal')
    plt.show()

def to_numpy(v):
    if isinstance(v, torch.Tensor):
        return v.detach().cpu().numpy()
    return v

In [ ]:
# Breakdown Eigen decomposition

